11. GET /api/reviews (queries)
MRombi/board-games-are-not-all-the-sames pull request #10
Opened 2022-07-07 11:41 UTC by MRombi

add query for sort_by, order and category(filter) with tests
Added checkUsernameById and tests to check if the username exists when posting comments

2022-07-07 14:11 UTC, douglashellowell commented on __tests__/app.test.js
> +        });
remember to include an assertion that the array (`reviews`) is not empty!

If it was empty your `forEach` would not invoke it's function and your jest test would automatically pass! 😱

2022-07-07 14:12 UTC, douglashellowell commented on __tests__/app.test.js
> +      .get("/api/reviews/?test=euro game")
no need for the `/` at the end of this path

```diff
-      .get("/api/reviews/?test=euro game")
+      .get("/api/reviews?test=euro game")
```

2022-07-07 14:16 UTC, douglashellowell commented on db/app/controllers/comments.c.js
> +    checkUsernameById(review_id, username),
this `checkUsernameById` check isn't strictly necassary - the `insertCommentByReviewId` model would have thrown an error if the username didn't exist already

2022-07-07 15:49 UTC, douglashellowell commented
Forgot to mention!

I've just noticed you've put all your code in `/db`!

You should only put the database-related files in here

2022-07-08 09:19 UTC, douglashellowell commented on db/app/models/reviews.m.js
> +    searchSort_by = sort_by;
this variable looks like its not being used anymore - is it left over from before the refactor?

2022-07-08 09:22 UTC, douglashellowell commented on db/app/models/comments.m.js
> +  RETURNING author, body;
👆 my previous comment still needs addressing here

2022-07-08 09:33 UTC, douglashellowell requested changes
nice work!

There is still a fix needed in your `insertCommentByReviewId` model (see my comment above)

---

still need to `200` test on a reviews about a category that does exist but doesn't have any reviews related to it

---

2022-07-08 11:09 UTC, Angaca approved these changes
Looks very good!

2022-07-08 11:12 UTC, merged